CREATE TABLE IF NOT EXISTS reservations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL COMMENT '회사명',
    representative VARCHAR(50) NOT NULL COMMENT '대표자명',
    phone VARCHAR(20) NOT NULL COMMENT '연락처',
    address VARCHAR(200) NOT NULL COMMENT '주소',
    business_number VARCHAR(20) NOT NULL COMMENT '사업자등록번호',
    tax_manager_name VARCHAR(50) NOT NULL COMMENT '세무담당자명',
    tax_manager_phone VARCHAR(20) NOT NULL COMMENT '세무담당자 연락처',
    tax_manager_email VARCHAR(100) NOT NULL COMMENT '세무담당자 이메일',
    purpose TEXT COMMENT '용도',
    total_people INT DEFAULT 0 COMMENT '총 인원',
    start_date DATE NOT NULL COMMENT '시작일',
    end_date DATE NOT NULL COMMENT '종료일',
    total_amount DECIMAL(15,2) DEFAULT 0 COMMENT '총 금액',
    contract_amount DECIMAL(15,2) DEFAULT 0 COMMENT '계약금액',
    balance_amount DECIMAL(15,2) DEFAULT 0 COMMENT '잔여금액',
    doc_tax_invoice TINYINT(1) DEFAULT 0 COMMENT '세금계산서',
    doc_card TINYINT(1) DEFAULT 0 COMMENT '카드영수증',
    doc_cash_receipt TINYINT(1) DEFAULT 0 COMMENT '현금영수증',
    doc_none TINYINT(1) DEFAULT 0 COMMENT '증빙없음',
    usage_accommodation TINYINT(1) DEFAULT 0 COMMENT '숙박',
    usage_hall TINYINT(1) DEFAULT 0 COMMENT '홀',
    usage_facility TINYINT(1) DEFAULT 0 COMMENT '시설',
    usage_etc TINYINT(1) DEFAULT 0 COMMENT '기타',
    status VARCHAR(20) DEFAULT 'pending' COMMENT '상태',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='예약 테이블'; 